---
sidebar: sidebar 
permalink: reference-provider-integrations.html 
keywords: maintenance event, azure maintenance event, cloud provider, issues, support, SMB CA in CVO 
summary: 本页介绍NetApp如何与云提供商合作解决可能出现的问题。 
---
= 与云提供商合作开发Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解NetApp如何与云提供商合作解决潜在问题。



== 协作支持最佳实践

NetApp致力于向被许可方提供支持，并将在被许可方报告Cloud Volumes ONTAP技术支持问题时采取商业上合理的努力来解决该问题。  NetApp和适用的云提供商对彼此的许可软件或基础设施没有任何直接支持义务。

NetApp已实施旨在与适用的云提供商联系的工具，以解决可能由适用的云提供商服务导致的客户技术问题。但是，保持无缝支持流程的最佳方式是客户 (i) 与NetApp和适用的云提供商保持当前的支持合同，以及 (ii) 在出现技术问题且客户需要明确哪些产品或服务导致这些技术问题时，与NetApp和适用的云提供商协调联合升级会议。



== Azure 维护事件

Microsoft 计划并以编程方式宣布其 Azure 虚拟机 (VM) 基础架构上的维护事件，这些事件可能会影响Cloud Volumes ONTAP VM。这些活动将在维护时段前 15 分钟宣布。

Cloud Volumes ONTAP高可用性 (HA) 对支持对维护事件进行特殊处理。为了保持应用程序的健康，我们执行预防性接管以优先考虑稳定性，因为任何超过 15 秒的连接丢失都会禁用故障转移功能。

当宣布维护窗口时，目标节点的伙伴节点将执行接管。维护完成后，将启动返还。恢复后，HA 对预计将恢复到健康状态。如果没有出现这种情况，请联系NetApp支持寻求帮助。请注意，维护事件每次仅针对 HA 对中的一个虚拟机，并且通常在相对较短的时间内同时针对两个节点。

使用Cloud Volumes ONTAP非连续可用 CIFS 共享的 CIFS/SMB 客户端在发生接管时以及会话所使用的聚合交还给聚合的主节点时，都会遇到会话丢失的情况。这是 CIFS/SMB 协议本身的限制。您可以使用经批准的第三方产品来避免接管和交还导致的问题。如需进一步帮助，请联系NetApp支持。


NOTE: https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["持续可用的 SMB 共享"^] Cloud Volumes ONTAP不支持无中断操作。
