---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, vm, flash cache 
summary: 这些已知限制特定于 Microsoft Azure 中的Cloud Volumes ONTAP 。 
---
= Azure 中Cloud Volumes ONTAP的已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
以下已知限制特定于 Microsoft Azure 中的Cloud Volumes ONTAP 。请务必查看link:reference-limitations.html["所有云提供商对Cloud Volumes ONTAP的限制"]。



== 使用 Azure VM 扩展的限制

Cloud Volumes ONTAP不支持 Azure 虚拟机 (VM) 扩展，因为它们会影响BlueXP管理操作。在部署期间， BlueXP会阻止在您的虚拟机上安装任何扩展。如果您现有的Cloud Volumes ONTAP VM 上已安装扩展，请联系 Microsoft Azure 支持将其删除。如需指导，请参阅知识库 (KB) 文章 https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Can_Azure_VM_Management_Extensions_be_installed_into_Cloud_Volume_ONTAP["Azure VM 管理扩展可以安装到 Cloud Volume ONTAP中吗？"^]

从 2025 年 7 月 14 日开始，如果在您的Cloud Volumes ONTAP VM 上检测到 VM 扩展， NetApp将发送电子邮件并在BlueXP中通知您。



== 闪存缓存限制

Cloud Volumes ONTAP使用某些 VM 类型中的本地 NVMe 存储作为_Flash Cache_。请注意此限制：

* 不支持重启后缓存重新预热。




== 高可用性部署的局限性

某些区域不支持高可用性 (HA) 对。

https://bluexp.netapp.com/cloud-volumes-global-regions["查看受支持的 Azure 区域列表"^] 。



== 单个可用区域中 HA 部署的限制

从Cloud Volumes ONTAP 9.15.1 开始，您可以在 Azure 中的单个可用区域 (AZ) 中以 HA 模式部署虚拟机 (VM) 实例。有关支持此功能的标准的信息，请参阅 https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#deploy-ha-pairs-in-single-availability-zones-on-azure["在 Azure 中的单个可用性区域中部署 HA 对"^]。

如果Cloud Volumes ONTAP版本早于 9.15.1 或者不满足上述任何条件，则先前利用可用性集的部署模型将生效。这仅适用于 HA 配置。
