---
sidebar: sidebar 
permalink: reference-configs-gcp.html 
keywords: google, gcp, google cloud platform, explore, standard, premium, byol, paygo, disks, supported, capacity, machine types, sizes, HA, high availability, HA pairs 
summary: Google Cloud 支持多种Cloud Volumes ONTAP配置。 
---
= Google Cloud 中Cloud Volumes ONTAP支持的配置
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud 支持多种Cloud Volumes ONTAP配置。



== 许可证支持的配置

Cloud Volumes ONTAP在 Google Cloud 中可作为单节点系统使用，也可作为高可用性 (HA) 节点对使用，以实现容错和无中断操作。

不支持将单节点系统升级到 HA 对。如果您想在单节点系统和 HA 对之间切换，则需要部署新系统并将数据从现有系统复制到新系统。

Cloud Volumes ONTAP可以在云提供商提供的预留或按需 VM 实例上运行。不支持使用其他 VM 实例类型的解决方案。

[role="tabbed-block"]
====
.基于容量的许可证
--
[cols="h,d,d,d"]
|===
|  | 免费增值 | 已优化^4^ | 基于容量的许可证（Essentials 和 Professional） 


| 最大系统容量（磁盘+对象存储） | 500 GiB  a| 
通过基于容量的许可，每个Cloud Volumes ONTAP系统都支持分层到对象存储。总分层容量可以扩展到云提供商的存储桶限制。虽然许可证没有施加容量限制，但您应该遵循 https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["FabricPool最佳实践"^]确保在配置和管理分层时实现最佳性能、可靠性和成本效率。



| 支持的机器类型^1^  a| 
* n1-标准-8 ^1^
* n1-标准-32 ^1^
* n2-标准-4
* n2-标准-8
* n2-标准-16
* n2-标准-32
* n2-标准-48
* n2-标准-64

 a| 
* n2-标准-4
* n2-标准-8

 a| 
* n1-标准-8 ^1^
* n1-标准-32 ^1^
* n2-标准-4
* n2-标准-8
* n2-标准-16
* n2-标准-32
* n2-标准-48
* n2-标准-64




| 支持的磁盘类型^2^ 3+| 平衡持久磁盘 ^3^、性能 (SSD) 持久磁盘 ^3^ 和标准 (HDD) 持久磁盘。 
|===
注：

. ^1^ 在 Google Cloud 中部署Cloud Volumes ONTAP的新实例时， BlueXP上不再可选择 n1 系列机器。 n1 系列机器将保留，并且仅在较旧的现有系统中得到支持。从 9.8 版本开始，Google Cloud 才支持Cloud Volumes ONTAP的新部署。我们建议您切换到与Cloud Volumes ONTAP 9.8 及更高版本兼容的 n2 系列机器。不过，n1 系列机器将可用于通过 API 进行的新部署。
+
新的Cloud Volumes ONTAP系统不再支持 custom-4-16384 机器类型。如果您现有的系统正在此机器类型上运行，您可以继续使用它，但我们建议切换到 n2-standard-4 机器类型。

. ^2^ 磁盘限制可以防止您仅通过使用磁盘就达到最大系统容量限制。您可以通过以下方式达到容量限制 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["将非活动数据分层到对象存储"^]。
+
link:reference-limits-gcp.html["详细了解 Google Cloud 中的磁盘限制"] 。

. ^3^ 使用平衡持久磁盘和性能（SSD）持久磁盘时，可启用增强写入性能。
+
从Cloud Volumes ONTAP 9.13.0 开始，_Flash Cache_、高写入速度以及更高的 8,896 字节最大传输单元 (MTU) 可用于以下 HA 对部署实例：

+
** n2-标准-16
** n2-标准-32
** n2-标准-48
** n2-标准-64
+
您可以在部署符合条件的实例类型时启用_Flash Cache_和高写入速度。要启用更高的 8,896 字节最大传输单元，您必须为部署选择 VPC-1、VPC-2 或 VPC-3。更高的 MTU 可实现更高的网络吞吐量。有关启动这些部署的更多信息，请参阅 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["在 Google Cloud 中启动 HA 对"]。

+

NOTE: _Flash 缓存_、高写入模式和 8,896 的 MTU 依赖于功能，无法在配置的实例中单独禁用。



. ^4^ 自 2025 年 8 月 11 日起， Cloud Volumes ONTAP Optimized 许可证将被弃用，并且将不再可在 Google Cloud 市场中以即用即付 (PAYGO) 订阅的方式购买或续订。有关信息，请参阅 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Cloud Volumes ONTAP的新功能"^]。


--
.基于节点的许可证
--
[cols="h,d,d,d,d"]
|===
|  | PAYGO 探索 | PAYGO 标准 | PAYGO 保费 | 基于节点的 BYOL 


| 最大系统容量（磁盘+对象存储） | 2 TB ^2^ | 10 TiB | 368 TiB | 每个许可证 368 TiB 


| 支持的机器类型^3^  a| 
* n2-标准-4

 a| 
* n1-标准-8 ^3^
* n2-标准-8

 a| 
* n1-标准-32 ^3^
* n2-标准-16
* n2-标准-32
* n2-标准-48
* n2-标准-64

 a| 
* n1-标准-8 ^3^
* n1-标准-32 ^3^
* n2-标准-4
* n2-标准-8
* n2-标准-16
* n2-标准-32
* n2-标准-48
* n2-标准-64




| 支持的磁盘类型 4+| 平衡持久磁盘 ^4^、性能 (SSD) 持久磁盘 ^4^ 和标准 (HDD) 持久磁盘。 
|===
注：

. ^1^ 磁盘限制可以防止您仅通过使用磁盘就达到最大系统容量限制。您可以通过以下方式达到容量限制 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["将非活动数据分层到对象存储"^]。
+
link:reference-limits-gcp.html["详细了解 Google Cloud 中的磁盘限制"] 。

. ^2^ PAYGO Explore 不支持将数据分层到 Google Cloud Storage。
. ^3^ 在 Google Cloud 中部署Cloud Volumes ONTAP的新实例时， BlueXP上不再可选择 n1 系列机器。 n1 系列机器将保留，并且仅在较旧的现有系统中得到支持。从 9.8 版本开始，Google Cloud 才支持Cloud Volumes ONTAP的新部署。我们建议您切换到与Cloud Volumes ONTAP 9.8 及更高版本兼容的 n2 系列机器。然而，n1 系列机器将可用于通过 API 执行的新部署。
+
新的Cloud Volumes ONTAP系统不再支持 custom-4-16384 机器类型。如果您现有的系统正在此机器类型上运行，您可以继续使用它，但我们建议切换到 n2-standard-4 机器类型。

. ^4^ 使用平衡持久磁盘和性能（SSD）持久磁盘时，可启用增强写入性能。


BlueXP界面显示了标准和 BYOL 支持的额外机器类型：n1-highmem-4。然而，这种机器类型并不适合生产环境。我们仅将其用于特定的实验室环境。

从Cloud Volumes ONTAP软件版本 9.13.0 开始，以下 HA 对部署实例可以使用_Flash Cache_、高写入速度以及更高的 8,896 字节最大传输单元 (MTU)：

* n2-标准-16
* n2-标准-32
* n2-标准-48
* n2-标准-64


您可以在部署符合条件的实例类型时启用_Flash Cache_和高写入速度。要启用更高的 8,896 字节最大传输单元，您必须为部署选择 VPC-1、VPC-2 或 VPC-3。更高的 MTU 可实现更高的网络吞吐量。有关启动这些部署的更多信息，请参阅 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["在 Google Cloud 中启动 HA 对"]。


NOTE: _Flash 缓存_、高写入模式和 8,896 的 MTU 依赖于功能，无法在配置的实例中单独禁用。

--
====
有关特定机器类型的更多信息，请参阅 Google Cloud 文档：

* https://cloud.google.com/compute/docs/general-purpose-machines#n1_machines["n1系列通用机型"^]
* https://cloud.google.com/compute/docs/general-purpose-machines#n2_series["N2系列通用机型"^]




== 支持的磁盘大小

在 Google Cloud 中，一个聚合最多可以包含 6 个类型和大小相同的磁盘。支持以下磁盘大小：

* 100 GB
* 500 GB
* 1 TB
* 2 TB
* 4 TB
* 8 TB
* 16 TB
* 64 TB




== 支持的区域

有关 Google Cloud 区域支持，请参阅 https://bluexp.netapp.com/cloud-volumes-global-regions["Cloud Volumes 全球区域"^]。
