---
sidebar: sidebar 
permalink: reference-limits-gcp.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM 
summary: 为了提供可靠的操作， Cloud Volumes ONTAP在 Google Cloud 中具有存储配置限制。为了获得最佳性能，请不要将系统配置为最大值。 
---
= Google Cloud 中Cloud Volumes ONTAP的存储限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP具有存储配置限制，以提供可靠的操作。为了获得最佳性能，请不要将系统配置为最大值。



== 许可证的最大系统容量

Cloud Volumes ONTAP系统的最大系统容量由其许可证决定。最大系统容量包括基于磁盘的存储以及用于数据分层的对象存储。

NetApp不支持超出系统容量限制。如果达到许可容量限制， BlueXP将显示需要操作的消息，并且不再允许您添加其他磁盘。

对于某些配置，磁盘限制会阻止您仅使用磁盘来达到容量限制。您可以通过以下方式达到容量限制 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["将非活动数据分层到对象存储"^]。请参阅下面的磁盘限制以了解更多详细信息。

.基于容量的许可证的容量限制
通过基于容量的许可，每个Cloud Volumes ONTAP系统都支持分层到对象存储。总分层容量可以扩展到云提供商的存储桶限制。虽然许可证没有施加容量限制，但您应该遵循 https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["FabricPool最佳实践"^]确保在配置和管理分层时实现最佳性能、可靠性和成本效率。请参阅 https://cloud.google.com/storage/docs/buckets["Google Cloud 文档"^]了解更多信息。

其他许可证类型的容量限制::


[cols="25,75"]
|===
| 许可证 | 最大系统容量（磁盘+对象存储） 


| 免费增值 | 500 GB 


| PAYGO 探索 | 2 TB（Explore 不支持数据分层） 


| PAYGO 标准 | 10 TB 


| PAYGO 保费 | 368 TB 


| 基于节点的许可证 | 2 PiB（需要多个许可证） 
|===
.对于 HA 对，许可容量限制是针对每个节点还是针对整个 HA 对？
容量限制针对的是整个 HA 对。它不是每个节点的。例如，如果您使用 Premium 许可证，则两个节点之间最多可以拥有 368 TB 的容量。

.对于 HA 对，镜像数据是否计入许可容量限制？
不，不是这样的。HA 对中的数据在节点之间同步镜像，以便在 Google Cloud 发生故障时数据可用。例如，如果您在节点 A 上购买了 8 TB 磁盘， BlueXP还会在节点 B 上分配一个 8 TB 磁盘用于镜像数据。虽然设置了 16 TB 的容量，但只有 8 TB 计入许可证限制。



== 总计限制

Cloud Volumes ONTAP将 Google Cloud Platform 磁盘分组为_聚合_。聚合为卷提供存储。

[cols="2*"]
|===
| 参数 | 限制 


| 最大数据聚合数^1^  a| 
* 单节点99
* 整个 HA 对为 64




| 最大骨料尺寸 | 256 TB 原始容量^2^ 


| 每个聚合的磁盘数 | 1-6 ^3^ 


| 每个聚合的最大 RAID 组数 | 1 
|===
注：

. 数据聚合的最大数量不包括根聚合。
. 组成聚合的磁盘决定了聚合容量限制。此限制不包括用于数据分层的对象存储。
. 聚合中的所有磁盘必须具有相同的大小。




== 磁盘和分层限制

下表显示了仅使用磁盘以及使用磁盘和冷数据分层到对象存储的最大系统容量。磁盘限制特定于包含用户数据的磁盘。这些限制不包括启动磁盘、根磁盘或NVRAM。

[cols="60,40"]
|===
| 参数 | 限制 


| 最大数据磁盘数  a| 
* 单节点系统为 124
* 对于 HA 对，每个节点 123 个




| 最大磁盘大小 | 64 TB 


| 仅使用磁盘的最大系统容量 | 256 TB^1^ 


| 磁盘和冷数据分层到 Google Cloud Storage 存储桶的最大系统容量 | 取决于许可证。请参阅上面的最大系统容量限制。 
|===
^1^ 此限制由 Google Cloud Platform 中的虚拟机限制定义。



== 存储虚拟机限制

某些配置使您能够为Cloud Volumes ONTAP创建额外的存储虚拟机 (SVM)。

这些是经过测试的极限。不支持配置更多存储虚拟机。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-gcp.html["了解如何创建额外的存储虚拟机"^] 。

[cols="2*"]
|===
| 许可证类型 | 存储虚拟机限制 


| *免费增值*  a| 
总共 24 个存储虚拟机^1^



| *基于容量的 PAYGO 或 BYOL* ^2^  a| 
总共 24 个存储虚拟机^1^



| *基于节点的 BYOL* ^3^  a| 
总共 24 个存储虚拟机^1^



| *基于节点的PAYGO*  a| 
* 1 个用于提供数据的存储虚拟机
* 1 个用于灾难恢复的存储虚拟机


|===
. 这 24 个存储虚拟机可以提供数据或配置用于灾难恢复 (DR)。
. 对于基于容量的许可，额外的存储虚拟机无需额外的许可费用，但每个存储虚拟机至少需支付 4 TiB 的容量费用。例如，如果您创建两个存储虚拟机，每个虚拟机具有 2 TiB 的预配置容量，则总共需要支付 8 TiB 的费用。
. 对于基于节点的 BYOL，除了默认随Cloud Volumes ONTAP附带的第一个存储虚拟机之外，每个额外的_数据服务_存储虚拟机都需要附加许可证。联系您的客户团队以获取存储 VM 附加许可证。
+
为灾难恢复 (DR) 配置的存储虚拟机不需要附加许可证（它们是免费的），但它们会计入存储虚拟机限制。例如，如果您有 12 个数据服务存储虚拟机和 12 个为灾难恢复配置的存储虚拟机，那么您已达到限制并且无法创建任何其他存储虚拟机。





== 逻辑存储限制

[cols="22,22,56"]
|===
| 逻辑存储 | 参数 | 限制 


.2+| *文件* | 最大尺寸^2^ | 128 TB 


| 每卷最大数量 | 取决于容量大小，最多 20 亿 


| * FlexClone卷* | 分层克隆深度^12^ | 499 


.3+| * FlexVol卷* | 每个节点的最大值 | 500 


| 大小上限 | 20 MB 


| 最大尺寸^3^ | 300 TiB 


| *Qtree* | 每个FlexVol volume的最大值 | 4,995 


| *快照副本* | 每个FlexVol volume的最大值 | 1,023 
|===
. 分层克隆深度是可从单个FlexVol volume创建的FlexClone卷嵌套层次结构的最大深度。
. 从ONTAP 9.12.1P2 开始，限制为 128 TB。在ONTAP 9.11.1 及更早版本中，限制为 16 TB。
. 使用以下工具和最低版本支持创建最大大小为 300 TiB 的FlexVol volume：
+
** 从Cloud Volumes ONTAP 9.12.1 P2 和 9.13.0 P2 开始的系统管理器和ONTAP CLI
** 从Cloud Volumes ONTAP 9.13.1 开始的BlueXP






== iSCSI 存储限制

[cols="3*"]
|===
| iSCSI存储 | 参数 | 限制 


.4+| *LUN* | 每个节点的最大值 | 1,024 


| 最大 LUN 映射数 | 1,024 


| 最小大小 | 16 TB 


| 每卷最大数量 | 512 


| *igroups* | 每个节点的最大值 | 256 


.2+| *发起者* | 每个节点的最大值 | 512 


| 每个 igroup 的最大值 | 128 


| iSCSI 会话 | 每个节点的最大值 | 1,024 


.2+| *LIF* | 每个端口的最大值 | 1 


| 每个端口集的最大值 | 32 


| *端口集* | 每个节点的最大值 | 256 
|===


== Cloud Volumes ONTAP HA 对不支持立即恢复存储

节点重启后，伙伴必须同步数据才能返回存储。重新同步数据所需的时间取决于节点关闭时客户端写入的数据量以及恢复期间的数据写入速度。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-google-cloud.html["了解在 Google Cloud 中运行的Cloud Volumes ONTAP HA 对中的存储工作原理"^] 。
