---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, detaching, snapmanager, features, disks, aggregates, features, svm 
summary: 已知限制标识了该产品的此版本不支持或不能与其正确互操作的平台、设备或功能。仔细审查这些限制。 
---
= 所有云提供商中Cloud Volumes ONTAP的已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
已知限制标识了该产品的此版本不支持或不能与其正确互操作的平台、设备或功能。仔细审查这些限制。

以下限制适用于所有云提供商中的Cloud Volumes ONTAP ：AWS、Azure 和 Google Cloud。



== 不受支持的ONTAP功能

Cloud Volumes ONTAP不支持以下功能：

* 聚合级在线重复数据删除
* 聚合级后台重复数据删除
* 磁盘维护中心
* 磁盘清理
* FabricPool镜像
* Fibre Channel（光纤通道）(FC)
* 闪存池
* 无限卷
* 接口组
* 节点内 LIF 故障转移
* MetroCluster
* 多管理员验证
+
在Cloud Volumes ONTAP上启用多管理员验证将导致不受支持的配置。

* RAID4、RAID-DP、 RAID-TEC （支持RAID0）
* 服务处理器
* SnapLock Compliance和企业模式（仅支持 Cloud WORM）
* SnapMirror同步
* VLAN
* SMB 持续可用性 (CA)
+
https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["持续可用的 SMB 共享"^]不支持无中断运行。





== 最大并发复制操作数

无论实例类型或机器类型如何， Cloud Volumes ONTAP 的最大并发SnapMirror或SnapVault传输数为每个节点 100 个。



== 云提供商快照不得用于您的备份和恢复计划

您不应将云提供商的快照用作Cloud Volumes ONTAP数据备份和恢复计划的一部分。您应该始终使用ONTAP Snapshot 副本或第三方备份解决方案来备份和恢复托管在Cloud Volumes ONTAP上的数据。

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["了解如何使用BlueXP backup and recovery来备份和恢复ONTAP数据"^] 。


NOTE: WAFL文件系统中的ONTAP一致性点决定数据一致性。只有ONTAP可以使WAFL文件系统静止以进行崩溃一致性备份。



== Cloud Volumes ONTAP仅支持预留和按需 VM 实例

Cloud Volumes ONTAP可以在云提供商提供的预留或按需 VM 实例上运行。不支持其他类型的 VM 实例。



== 不应使用自动应用程序资源管理解决方案

自动应用程序资源管理解决方案不应管理Cloud Volumes ONTAP系统。这样做可能会导致更改不受支持的配置。例如，解决方案可能会将Cloud Volumes ONTAP更改为不受支持的 VM 实例类型。



== 软件更新必须由BlueXP完成

Cloud Volumes ONTAP的升级必须从BlueXP完成。您不应使用系统管理器或 CLI 升级Cloud Volumes ONTAP 。这样做会影响系统稳定性。



== 不得从云提供商的控制台修改Cloud Volumes ONTAP部署

从云提供商的控制台更改Cloud Volumes ONTAP配置会导致配置不受支持。  BlueXP创建和管理的Cloud Volumes ONTAP资源的任何更改都可能影响系统稳定性和 BlueXP 管理系统的能力。


NOTE: 初始部署后，支持修改用于Cloud Volumes ONTAP资源的 Azure 订阅名称。



== 磁盘和聚合必须由BlueXP管理

所有磁盘和聚合都必须直接从BlueXP创建和删除。您不应从其他管理工具执行这些操作。这样做会影响系统稳定性，妨碍将来添加磁盘的能力，并可能产生冗余的云提供商费用。



== SnapManager许可限制

Cloud Volumes ONTAP支持SnapManager每服务器许可证。不支持每个存储系统（ SnapManager套件）许可证。



== 第三方代理和扩展的局限性

Cloud Volumes ONTAP虚拟机实例不支持第三方代理和 VM 扩展。
